version: "3.8"
services:
  mysql-new:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3308'
  mysql-legacy:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3308'
    